TELEGRAM_TOKEN = '5908266258:AAGjwTsYJr_mZS3UILDx8hzpiyhlHCIAquU'
OPENAI_TOKEN = '5908266258:AAGjwTsYJr_mZS3UILDx8hzpiyhlHCIAquU'
MONGODB_CONNECTION_STRING = 'mongodb+srv://markiyanch:IiGPXXLIyyoTw4JL@cluster0.soznvr3.mongodb.net/?retryWrites=true&w=majority'
PAYMENT_TOKEN = ''

QUESTIONS_COUNT = 3
REFERRALS_NEEDED = 3